// ════════════════════════════════════════════════════════
// CONSTANTES COMPARTILHADAS — itens de cada formulário ATE
// Carregado por: index.html, compilado.html
// ════════════════════════════════════════════════════════

// ════════════════════════════════════════════════════════
// DATA - INFRAESTRUTURA (também usado por Almoxarifado)
// ════════════════════════════════════════════════════════
const infraItems = [
  { num: 1, desc: "Equipamento de refrigeração em bom estado, para guarda e conservação de alimentos." },
  { num: 2, desc: "Água potável, filtrada, para os trabalhadores por meio de bebedouros ou equipamento similar." },
  { num: 3, desc: "Produtos inflamáveis e químicos armazenados adequadamente em local apropriado." },
  { num: 4, desc: "Reservatório de água com capacidade aproximada de 60 litros diários por trabalhador. O reservatório ou bebedouro é limpo periodicamente." },
  { num: 5, desc: "Aparelhos e sistema de ar condicionado inspecionados e limpos periodicamente." },
  { num: 6, desc: "Existência e implantação do PSCIP – processo de segurança contra incêndio e pânico. A instalação possui o projeto de combate a incêndio e o AVCB atualizados." },
  { num: 7, desc: "Existência de equipamentos de proteção contra incêndio onde aplicável (extintores, hidrantes, sprinklers, etc.)." },
  { num: 8, desc: "Pisos do local de trabalho livres de depressões ou saliências que prejudiquem a circulação de pessoas ou a movimentação de materiais." },
  { num: 9, desc: "Emprego de materiais antiderrapantes e corrimãos onde houver perigo de escorregamento nos pisos, escadas, rampas, corredores e passagens dos locais de trabalho." },
  { num: 10, desc: "Materiais armazenados de forma a evitar a obstrução de portas, equipamentos contra incêndio e saídas de emergência." },
  { num: 11, desc: "Vias de circulação de pessoas e máquinas sinalizadas e pré-definidas em locais com alto potencial de risco." },
  { num: 12, desc: "Existência de sinalização de segurança e de emergência." },
  { num: 13, desc: "Prateleiras, estantes, escaninhos e armações robustas e adequadas ao tipo de material armazenado." },
  { num: 14, desc: "Local destinado a refeição fora do local de trabalho, limpo, arejado, com boa iluminação, piso lavável, com mesas e assentos em bom estado de conservação, e lavatórios e pias próximos ao local." },
  { num: 15, desc: "Estufa, fogão ou similar para aquecimento de refeição, sendo proibida a utilização de álcool para este fim." },
  { num: 16, desc: "Iluminação adequada ao ambiente." },
  { num: 17, desc: "Conforto térmico adequado ao ambiente." },
  { num: 18, desc: "Existência de guarda-corpo nos andares acima do solo. Tais como: terraços, balcões, compartimentos para garagens, etc." },
  { num: 19, desc: "Os banheiros e vestiários são em número suficiente para atender os empregados." },
  { num: 20, desc: "Resíduos industriais devidamente separados, em locais disponíveis para coleta." },
  { num: 21, desc: "As instalações elétricas estão adequadamente protegidas. (Caixas com tampa, fiação dentro de eletrodutos, conexões isoladas, bebedouros e chuveiros aterrados)." },
  { num: 22, desc: "Pia exclusiva para lavar os alimentos e utensílios." },
  { num: 23, desc: "Os botijões de GLP estão instalados fora do ambiente de utilização, em área permanentemente ventilada e coberta. Válvula e mangueira aprovados pelo INMETRO e dentro da validade." },
  { num: 24, desc: "As instalações sanitárias possuem paredes e piso impermeável, lavável, o piso inclinado para ralos de escoamento com sifões e não apresentam ressaltos/saliências e portas individuais por sanitário." },
  { num: 25, desc: "A instalação sanitária possui lavatório, vaso sanitário com assento e caixa de descarga ou válvula automática, na proporção de 1 conjunto para cada grupo de 20 trabalhadores." },
  { num: 26, desc: "Possui local para armazenamento de alimentos, separado dos produtos de limpeza." },
  { num: 27, desc: "O chuveiro possui água quente e está na proporção de 01 para cada grupo de 10 trabalhadores." },
  { num: 28, desc: "A cobertura ou laje protege contra chuva e a instalação não está situada em subsolo ou porões." },
  { num: 29, desc: "Equipe multidisciplinar indicada, espaços confinados reconhecidos, identificados, sinalizados e com registros atualizados." },
  { num: 30, desc: "Manter o ambiente livre de focos de reprodução de mosquitos." },
  { num: 31, desc: "Os equipamentos de proteção contra incêndio estão selados, sinalizados e com a inspeção em dia." },
  { num: 32, desc: "O estabelecimento possui alvará de licença e funcionamento para as atividades desenvolvidas." },
  { num: 33, desc: "Cadeira com altura ajustável, rodízios, borda frontal arredondada, encosto com forma levemente adaptada ao corpo para proteção da região lombar, pouca ou nenhuma conformação no assento." },
  { num: 34, desc: "Mapa de risco em local visível e atualizado." },
  { num: 35, desc: "Mesa sem quinas vivas e sem tampa de vidros." },
  { num: 36, desc: "Monitor e mesa atendem as condições antropométricas dos trabalhadores." },
  { num: 39, desc: "Existência de vestiário com armários individuais, bom estado de conservação e com aberturas para ventilação ou portas teladas." },
  { num: 40, desc: "Materiais e equipamentos armazenados adequadamente." },
  { num: 41, desc: "Canteiro de obra/estabelecimento organizado, limpo e desimpedido, notadamente nas vias de circulação, passagens e escadarias." },
  { num: 42, desc: "O local para refeições possui nº de assentos e mesas com tampos lisos e laváveis, suficientes para atender os trabalhadores." },
  { num: 43, desc: "Layout adequado ao material armazenado." },
  { num: 44, desc: "Local apropriado para armazenamento e destinação de resíduos." },
  { num: 45, desc: "Parte não pavimentada da instalação capinada e limpa." },
  { num: 46, desc: "Banheiros e instalações sanitárias higienizados, com água, sabão e papel toalha e higiênico disponíveis." },
  { num: 47, desc: "Possui recipiente com tampa na cozinha e banheiro para coleta de lixo. Os resíduos são retirados e armazenados em local adequado periodicamente." },
  { num: 48, desc: "A instalação sanitária possui papel higiênico e o lavatório possui material para a limpeza, enxugo ou secagem das mãos, proibindo-se o uso de toalhas coletivas." },
  { num: 49, desc: "Produto químico possui FISPQ?" },
  { num: 50, desc: "A instalação está livre de insetos e roedores, não necessitando de dedetização." },
];

// ════════════════════════════════════════════════════════
// DATA - MOTOCICLISTAS
// ════════════════════════════════════════════════════════
const motoFerramentas = [
  { num: 1, desc: "Alicate profissional com cabo isolado", uni: "Pç", qty: 1 },
  { num: 2, desc: "Alicate de corte diagonal com cabo isolado", uni: "Pç", qty: 1 },
  { num: 3, desc: "Analisador de Desvio de Registro (**)", uni: "Pç", qty: 1, laudo: 1, fabs: [], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "Conserve", "Engelmig"] },
  { num: 4, desc: "Bastão de manobra ou vara telescópica com cabeçote universal com no mínimo 6 peças extensíveis e sacola para acondicionar", uni: "Pç", qty: 1, laudo: 1, fabs: ["Montrel"] },
  { num: 6, desc: "Canivete, lâmina tipo navalha", uni: "Pç", qty: 1 },
  { num: 7, desc: "Chave canhão de 3/8\" isolada (isolamento de cabo e extensão)", uni: "Pç", qty: 1 },
  { num: 8, desc: "Chave canhão de 7/16\" isolada (isolamento de cabo e extensão)", uni: "Pç", qty: 1 },
  { num: 9, desc: "Chave com catraca com cabo isolado p/ aplicação de conector perfuração", uni: "Pç", qty: 1 },
  { num: 10, desc: "Chave de fenda isolada 6,5 x 150mm (isolamento de cabo e extensão)", uni: "Pç", qty: 1 },
  { num: 11, desc: "Chave de fenda isolada 3 x 100mm (isolamento de cabo e extensão)", uni: "Pç", qty: 1 },
  { num: 12, desc: "Chave de fenda isolada 5,5 x 150mm (isolamento de cabo e extensão)", uni: "Pç", qty: 1 },
  { num: 13, desc: "Chave Phillips isolada (isolamento de cabo e extensão) 6 x 150 mm", uni: "Pç", qty: 1 },
  { num: 14, desc: "Chave Phillips isolada (isolamento de cabo e extensão) 3 x 100 mm", uni: "Pç", qty: 1 },
  { num: 15, desc: "Chave inglesa 200mm isolada (isolamento de cabo e extensão)", uni: "Pç", qty: 1 },
  { num: 17, desc: "Colete com suporte para câmera, resistente a chama", uni: "Un", qty: 1 },
  { num: 19, desc: "Conjunto chave allen em mm de 8; 6; 5; 4; 3; 2,5 e 2", uni: "Cj", qty: 1 },
  { num: 20, desc: "Conjunto chave allen em polegadas de 1/4; 7/32; 3/16; 5/32; 9/64; 1/8; 7/64; 3/32 e 5/64", uni: "Cj", qty: 1 },
  { num: 22, desc: "Crachá de identificação com nome e número de registro do empregado", uni: "Pç", qty: 1 },
  { num: 25, desc: "Dispositivo de corte de ramal", uni: "Pç", qty: 1 },
  { num: 27, desc: "Equipamento de comunicação de dados e voz conforme especificação da Contratante (incluindo câmera e GPS)", uni: "Pç", qty: 1 },
  { num: 28, desc: "Inflador ou testador de luvas de borracha (*)", uni: "Pç", qty: 1 },
  { num: 29, desc: "Impressora Térmica Portátil", uni: "Pç", qty: 1, laudo: 1, fabs: ["ZEBRA RW420", "ZEBRA ZQ520", "ZEBRA ZQ521", "BIXOLON XM7-40"] },
  { num: 30, desc: "Lanterna para capacete ou manual", uni: "Pç", qty: 1 },
  { num: 32, desc: "Volt-amperímetro alicate classe IV", uni: "Pç", qty: 1, laudo: 1, labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "Conserve", "Engelmig"] },
];

const motoEpis = [
  { num: 33, desc: "Balaclava resistente a chama", uni: "Un", qty: 2 },
  { num: 34, desc: "Bolsa de Lona para acondicionar capacete, luva de vaqueta e óculos", uni: "Un", qty: 1 },
  { num: 35, desc: "Bolsa para acondicionar luva isolante", uni: "Un", qty: 1 },
  { num: 36, desc: "Bota de Segurança Cano Longo (BOTA DE CAMPANHA)", uni: "Pr", qty: 2 },
  { num: 37, desc: "Bota impermeável – cano longo – de borracha", uni: "Pr", qty: 1 },
  { num: 38, desc: "Calça de Uniforme com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas, com logotipo empresa", uni: "Un", qty: 3 },
  { num: 39, desc: "Camisa de Uniforme manga longa com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas com logotipo empresa", uni: "Un", qty: 3 },
  { num: 40, desc: "Capa impermeável para chuva (calça e blusa separadas, com faixa reflexiva)", uni: "Un", qty: 1 },
  { num: 41, desc: "Capacete de segurança, classe B, com aba frontal e jugular", uni: "Un", qty: 1 },
  { num: 43, desc: "Jaqueta de Uniforme com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas com logotipo empresa", uni: "Un", qty: 1 },
  { num: 44, desc: "Joelheira, cotoveleira de proteção e Luvas de motociclista (equipamentos de proteção do motociclista). A luva deve ter fechamento no punho.", uni: "Cj", qty: 1 },
  { num: 45, desc: "Luva de borracha isolante 0,5kV (classe 00)", uni: "Pr", qty: 1, laudo: 1, fabs: ["Salisbury", "North Safety", "GB", "Orion"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "Conserve", "Engelmig"] },
  { num: 47, desc: "Luva de couro para proteção da luva de borracha isolante", uni: "Pr", qty: 1 },
  { num: 48, desc: "Luva de vaqueta para trabalho leve", uni: "Pr", qty: 1 },
  { num: 49, desc: "Óculos de segurança incolor para proteção de partículas multidirecionais", uni: "Un", qty: 1 },
  { num: 50, desc: "Óculos de segurança lente escura tonalidade 2 ou 3 para proteção de partículas multidirecionais", uni: "Un", qty: 1 },
  { num: 51, desc: "Protetor solar FPS 30", uni: "Un", qty: 1 },
];

const motoChecklistVeiculo = [
  "Documentação atualizada",
  "Controle de manutenção (físico ou digital)",
  "Câmera veicular",
  "Rastreador veicular",
  "Antena dupla",
  "Baú de 90L",
  "Baú com fixação de varas internas",
  "Baú com faixas reflexivas",
  "Baú com identificação 'a serviço da CEMIG'",
  "Mata cachorro (aço tubular em peça única)",
  "Pneu em condições de uso (s/ reformar)",
  "Funilaria em boas condições",
  "Todas as setas em correto funcionamento",
  "Farol baixo e alto em correto funcionamento",
  "Buzina em correto funcionamento",
  "Capacete em bom estado de conservação",
  "Capacete com faixa reflexiva",
  "Viseira escamoteável ou de abertura total",
  "Viseira transparente em condições de uso",
  "Manete/manopla em condições de uso",
];

// ════════════════════════════════════════════════════════
// DATA - ES2
// ════════════════════════════════════════════════════════
const es2Ferramentas = [
  { num: 1, desc: "Alicate bomba d'água com cabo isolado", uni: "Pç", qty: 2 },
  { num: 2, desc: "Alicate de compressão hidráulico (com corda e gancho)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Solução", "Hubbel", "Izumi", "Grenlee"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 3, desc: "Alicate de compressão mecânica (com corda e gancho) (OPCIONAL se substituído por alicate de compressão hidráulico)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 4, desc: "Alicate de compressão eletro-hidráulico (com corda e gancho) (*)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Solução", "Hubbel", "Izumi", "Grenlee"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 5, desc: "Alicate profissional com cabo isolado", uni: "Pç", qty: 2 },
  { num: 6, desc: "Amperímetro, voltímetro, ohmímetro, alicate, digital, display LCD", uni: "Pç", qty: 2, laudo: 3, fabs: ["Hidramaq", "Solução", "Hubbel", "Izumi", "Grenlee"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 7, desc: "Analisador de Desvio de Registros (**)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Montrel"] },
  { num: 8, desc: "Arco de serra com lâmina", uni: "Pç", qty: 1 },
  { num: 9, desc: "Bandeirolas para sinalização e suporte para fixação", uni: "Pç", qty: 10 },
  { num: 11, desc: "Bastão pega-tudo cabeçote alumínio 32mm x 2600mm e sacola para acondicionar", uni: "Pç", qty: 1, laudo: 1, fabs: ["Terex"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 12, desc: "Binóculo", uni: "Pç", qty: 1 },
  { num: 13, desc: "Bolsa de lona porta fusível", uni: "Pç", qty: 1 },
  { num: 14, desc: "Cabeçote, manobra, para grampo de aterramento", uni: "Pç", qty: 1 },
  { num: 15, desc: "Cabeçote para corte de ramal de ligação até 35 mm²", uni: "Pç", qty: 1 },
  { num: 16, desc: "Cabo isolado 1x53mm² (1x1/0) com garra para by-pass – 4 metros", uni: "Un", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 17, desc: "Calibrador portátil para ensaio em medidor kWh eletromecânico e eletrônico (**)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 20, desc: "Calço emborrachado para veículo (veículos com estabilizador deverão também conter calços poliméricos para as sapatas)", uni: "Pç", qty: 2 },
  { num: 23, desc: "Câmera com sensor de fadiga que registre os eventos, emita alerta sonoro e visual (OPICIONAL)", uni: "Pç", qty: 1 },
  { num: 25, desc: "Câmera veicular conforme especificação da IT-RD-00022", uni: "Pç", qty: 1 },
  { num: 26, desc: "Canivete", uni: "Pç", qty: 2 },
  { num: 31, desc: "Catraca para 750 daN", uni: "Pç", qty: 1 },
  { num: 32, desc: "Cavadeira com socador, comprimento de 1500 mm", uni: "Pç", qty: 1 },
  { num: 36, desc: "Chave canhão de 3/8\" isolada (isolamento de cabo e extensão) – isolamento >= 1kV", uni: "Pç", qty: 2 },
  { num: 37, desc: "Chave canhão de 7/16\" isolada (isolamento de cabo e extensão) – isolamento >= 1kV", uni: "Pç", qty: 2 },
  { num: 38, desc: "Chave com catraca com cabo isolado para aplicação de conector perfuração", uni: "Pç", qty: 2 },
  { num: 39, desc: "Chave de fenda isolada (isolamento de cabo e extensão) 6,5 x 150mm", uni: "Pç", qty: 2 },
  { num: 40, desc: "Chave de fenda isolada (isolamento de cabo e extensão) 3 x 100mm", uni: "Pç", qty: 2 },
  { num: 41, desc: "Chave de fenda isolada (isolamento de cabo e extensão) 5,5 x 150mm", uni: "Pç", qty: 2 },
  { num: 42, desc: "Chave de impacto a bateria 180 Nm (com corda e gancho)", uni: "Pç", qty: 1 },
  { num: 43, desc: "Chave Phillips isolada (isolamento de cabo e extensão) 6 x 150mm", uni: "Pç", qty: 2 },
  { num: 44, desc: "Chave Phillips isolada (isolamento de cabo e extensão) 3 x 100mm (**)", uni: "Pç", qty: 1 },
  { num: 45, desc: "Chave inglesa 200mm isolada", uni: "Pç", qty: 2 },
  { num: 46, desc: "Chave inglesa 300mm isolada", uni: "Pç", qty: 2 },
  { num: 48, desc: "Computador notebook (**)", uni: "Pç", qty: 1 },
  { num: 49, desc: "Cone de sinalização, altura mínima 700mm", uni: "Pç", qty: 10 },
  { num: 50, desc: "Conjunto chave allen em mm de 8; 6; 5; 4; 3; 2,5 e 2", uni: "Cj", qty: 1 },
  { num: 51, desc: "Conjunto chave allen em polegadas de 1/4; 7/32; 3/16; 5/32; 9/64; 1/8; 7/64; 3/32 e 5/64", uni: "Cj", qty: 1 },
  { num: 52, desc: "Chave hexagonal Allen 5 mm, tipo T", uni: "Pç", qty: 1 },
  { num: 53, desc: "Conjunto de aterramento temporário para baixa tensão", uni: "Cj", qty: 2, laudo: 2, fabs: ["Terex", "Solução", "FCP"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 54, desc: "Conjunto de aterramento temporário para média tensão monofásico", uni: "Cj", qty: 2, laudo: 2, fabs: ["Terex", "Solução", "FCP"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 55, desc: "Conjunto de aterramento temporário para média tensão trifásico", uni: "Cj", qty: 2, laudo: 2, fabs: ["Terex", "Solução", "FCP"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 56, desc: "Conjunto de aterramento temporário sela com grampo de aterramento e haste", uni: "Cj", qty: 3, laudo: 3, fabs: ["Terex"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 57, desc: "Crachá de identificação", uni: "Pç", qty: 2 },
  { num: 58, desc: "Decapador de cabos para RDC", uni: "Pç", qty: 1 },
  { num: 59, desc: "Degrau de Fibra", uni: "Pç", qty: 4 },
  { num: 61, desc: "Detector de MT de 1 a 35 kV", uni: "Pç", qty: 1, laudo: 1, fabs: ["Terex", "Solução", "Lider", "Steetc"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 63, desc: "Dinamômetro 45 kgf para teste de padrão de entrada", uni: "Pç", qty: 1, laudo: 1, fabs: [], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 64, desc: "Dispositivo anti-queda de cartucho", uni: "Pç", qty: 1 },
  { num: 65, desc: "Dispositivo by-pass para chave fusível (*)", uni: "Pç", qty: 1 },
  { num: 66, desc: "Dispositivo de abertura em carga para MT", uni: "Pç", qty: 1, laudo: 1, fabs: ["Leal", "S&C", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 67, desc: "Dispositivo de fixação de placas de advertência", uni: "Pç", qty: 5 },
  { num: 68, desc: "Dispositivos instaladores de linha de vida (agulhão + gancho)", uni: "Cj", qty: 1 },
  { num: 74, desc: "Equipamento de comunicação de dados e voz conforme especificação da Contratante (incluindo câmera fotográfica e GPS)", uni: "Pç", qty: 1 },
  { num: 75, desc: "Escada de extensão 2 x 4,25m (± 0,5m) de fibra", uni: "Pç", qty: 2 },
  { num: 76, desc: "Escada singela 1 x 3,50m (± 0,5m) de fibra", uni: "Pç", qty: 1 },
  { num: 77, desc: "Escova de aço tubular para condutores", uni: "Pç", qty: 2 },
  { num: 78, desc: "Espora de aço DT", uni: "Pç", qty: 2 },
  { num: 80, desc: "Esticador com correia ou moitão de 2 gornes para condutores CA/CAA", uni: "Pç", qty: 1 },
  { num: 84, desc: "Estropo Cinta Tubular de 1m com identificação indelével da capacidade de carga 1000 daN", uni: "Pç", qty: 2 },
  { num: 86, desc: "Ferramenta para aplicação de conector cunha (para chave de impacto)", uni: "Pç", qty: 1 },
  { num: 87, desc: "Ferramenta para inspeção de poste de madeira", uni: "Pç", qty: 1 },
  { num: 88, desc: "Fita de isolamento com recolhedor, zebrada amarela e preta 50 mm x 40 m", uni: "Pç", qty: 2 },
  { num: 91, desc: "Garra para cabo CA/CAA 2/0 a 336", uni: "Pç", qty: 2 },
  { num: 92, desc: "Garra para cabo CA/CAA 6 a 1/0", uni: "Pç", qty: 2 },
  { num: 93, desc: "Garra para cabo de aço 6,4mm a 9,5mm", uni: "Pç", qty: 2 },
  { num: 94, desc: "Grampo para aterramento temporário chave fusível", uni: "Pç", qty: 3 },
  { num: 95, desc: "Grampo prendedor de lençol", uni: "Pç", qty: 8 },
  { num: 96, desc: "Impressora Térmica Portátil", uni: "Pç", qty: 1, laudo: 1, hasSN: false, hasValidade: false, hasLaudoName: false, fabs: ["ZEBRA RW420", "ZEBRA ZQ520", "ZEBRA ZQ521", "BIXOLON XM7-40"] },
  { num: 97, desc: "Inflador ou testador de luvas de borracha (*)", uni: "Pç", qty: 1 },
  { num: 99, desc: "Kit Antirreprova (**)", uni: "Pç", qty: 1 },
  { num: 100, desc: "Lâmina de serra", uni: "Pç", qty: 1 },
  { num: 101, desc: "Lanterna", uni: "Pç", qty: 2 },
  { num: 102, desc: "Lençol de borracha isolante para BT e sacola para acondicionar", uni: "Pç", qty: 10, laudo: 10, labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 105, desc: "Lima murça chata", uni: "Pç", qty: 1 },
  { num: 107, desc: "Marreta de aço de 2,5 kg", uni: "Pç", qty: 1 },
  { num: 108, desc: "Martelo bola", uni: "Pç", qty: 1 },
  { num: 110, desc: "Matriz para alicate hidráulico (162, 163, 236, 237, 238, 239, 242, 243, 245, 248, 249, 251, 252, 316, 321, D3, N e O)", uni: "Cj", qty: 1 },
  { num: 111, desc: "Matriz para alicate mecânico (162, 163, 236, 237, 238, 239, 242, 243 e 245)", uni: "Cj", qty: 1 },
  { num: 114, desc: "Moitão de 3 gornes de 1800 daN", uni: "Pç", qty: 1 },
  { num: 116, desc: "Motopoda elétrica ou hidráulica", uni: "Pç", qty: 1 },
  { num: 118, desc: "Motosserra elétrica portátil ou à combustão", uni: "Pç", qty: 1 },
  { num: 120, desc: "Parafusadeira a bateria com engate rápido para bit hexagonal de 1/4", uni: "Pç", qty: 1 },
  { num: 122, desc: "Placa de advertência 'não opere esta chave'", uni: "Pç", qty: 5 },
  { num: 125, desc: "Ponteiro de aço 1/2 pol de mão", uni: "Pç", qty: 1 },
  { num: 126, desc: "Recipiente aprovado pelo INMETRO para transporte e armazenamento de combustível para motosserra (*)", uni: "Pç", qty: 1 },
  { num: 128, desc: "Registrador de tensão e Corrente BT - Mód. 8 PRODIST com GPRS", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 129, desc: "Sacola para ferramentas", uni: "Un", qty: 1 },
  { num: 130, desc: "Sacola, p/ bastão telescópico (vara manobra) c/ terminal universal", uni: "Pç", qty: 1 },
  { num: 132, desc: "Serrote curvo para poda", uni: "Pç", qty: 1 },
  { num: 133, desc: "Sonda boroscópica 5m", uni: "Pç", qty: 1 },
  { num: 134, desc: "Sonda, passa fio, cabo de 20 m", uni: "Pç", qty: 1 },
  { num: 135, desc: "Suporte isolado para 1000 V,", uni: "Pç", qty: 1 },
  { num: 138, desc: "Tesourão articulado 750mm (com corda e gancho)", uni: "Pç", qty: 1 },
  { num: 140, desc: "Trado aço de 3/8\" para madeira", uni: "Pç", qty: 1 },
  { num: 141, desc: "Trena de fibra de 50m", uni: "Pç", qty: 1 },
  { num: 142, desc: "Vara, manobra, telescópica, 7 seções, fibra", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
];

const es2Epis = [
  { num: 144, desc: "Bolsa de Lona para acondicionar capacete, luva de vaqueta e óculos", uni: "Un", qty: 2 },
  { num: 145, desc: "Bolsa de Lona para acondicionar manga isolante", uni: "Un", qty: 2 },
  { num: 146, desc: "Bolsa para acondicionar luva isolante", uni: "Un", qty: 4 },
  { num: 147, desc: "Botina de Segurança com cadarço", uni: "Pr", qty: 4 },
  { num: 148, desc: "Calça de Uniforme com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas, com logotipo empresa", uni: "Un", qty: 6 },
  { num: 149, desc: "Camisa de Uniforme manga longa com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas com logotipo empresa", uni: "Un", qty: 6 },
  { num: 150, desc: "Capacete de segurança, classe B, com aba frontal e jugular", uni: "Un", qty: 2 },
  { num: 151, desc: "Capuz de proteção solar com tecido Resistente à Chama", uni: "Un", qty: 2 },
  { num: 153, desc: "Capa impermeável para chuva (calça e blusa separadas, com faixa reflexiva)", uni: "Un", qty: 2 },
  { num: 154, desc: "Carretilha de dupla ação com corda e gancho para trabalho e resgate", uni: "Un", qty: 2, laudo: 3 },
  { num: 155, desc: "Conjunto cinto paraquedista, talabarte de posicionamento com mosquetão de alumínio tripla trava e trava quedas", uni: "Cj", qty: 2, laudo: ["Cinto", "Talabarte", "Trava Quedas", "Cinto", "Talabarte", "Trava Quedas", "Cinto", "Talabarte", "Trava Quedas"], hasSN: false },
  { num: 156, desc: "Conjunto composto por abafador de ruídos tipo concha, protetor facial acrílico e kit de montagem para utilização através do encaixe nas fendas laterais do capacete aba frontal tipo boné.", uni: "Pç", qty: 1 },
  { num: 157, desc: "Corda de linha de vida 12mm – normatizadas pela NR18 (Cabos de fibra sintética) – 15 metros", uni: "Pç", qty: 2 },
  { num: 158, desc: "EPI para operador de Motosserra – Capacete com viseira acoplado com abafador de ruído tipo concha, luvas, botina com biqueira e calça especificadas para a atividade", uni: "Pç", qty: 1 },
  { num: 159, desc: "Garrafa térmica de 5 litros (1 garrafa para cada 2 pessoas)", uni: "Un", qty: 1 },
  { num: 160, desc: "Jaqueta de Uniforme com Tecido Resistente à Chama (OPCIONAL, de acordo com a necessidade da região)", uni: "Un", qty: 2 },
  { num: 161, desc: "Luva de borracha isolante 0,5kV (classe 00)", uni: "Pr", qty: 2, laudo: ["Luva 1", "Luva 2", "Luva 1", "Luva 2", "Luva 1", "Luva 2"], fabs: ["Salisbury", "Northsafety", "GB", "Orion"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 162, desc: "Luva de borracha Isolante 17kV (classe 2) ou 26,5kV (classe 3) – Conforme nível de tensão da região", uni: "Pr", qty: 2, laudo: ["Luva 1", "Luva 2", "Luva 1", "Luva 2", "Luva 1", "Luva 2"], fabs: ["Salisbury", "Northsafety", "GB", "Orion"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 164, desc: "Luva de segurança para operador de motosserra", uni: "Pç", qty: 1 },
  { num: 165, desc: "Luva de couro para proteção da luva de borracha isolante", uni: "Pr", qty: 4 },
  { num: 166, desc: "Luva de vaqueta para trabalho leve", uni: "Pr", qty: 2 },
  { num: 167, desc: "Manga isolante para 1kV – (Classe 0)", uni: "Pr", qty: 2, laudo: ["Manga 1", "Manga 2", "Manga 1", "Manga 2", "Manga 1", "Manga 2"], fabs: ["Salisbury", "GB"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 168, desc: "Mosquetão de aço dupla trava 22kN (para pontos de ancoragem)", uni: "Pç", qty: 4 },
  { num: 169, desc: "Óculos de segurança incolor para proteção de partículas multidirecionais", uni: "Un", qty: 2 },
  { num: 170, desc: "Óculos de segurança lente escura tonalidade 2 ou 3 para proteção de partículas multidirecionais", uni: "Un", qty: 2 },
  { num: 171, desc: "Perneira de couro sem partes metálicas ou Bota de Campanha", uni: "Pr", qty: 2 },
  { num: 173, desc: "Protetor solar FPS 30", uni: "Un", qty: 2 },
  { num: 174, desc: "Sacola de Lona para acondicionar ferramenta e EPIs (catarina)", uni: "Un", qty: 2 },
  { num: 175, desc: "Sacola de Lona para acondicionar linha de vida e cinto", uni: "Un", qty: 2 },
];

const es2Kit = [
  { num: 1, desc: "Caixa de ferramentas para acondicionamento dos itens – Capacidade Média 10L", uni: "PÇ", qty: 1 },
  { num: 2, desc: "Cadeado médio", uni: "PÇ", qty: 1 },
  { num: 3, desc: "Talhadeira tamanho Médio (25 cm)", uni: "PÇ", qty: 1 },
  { num: 4, desc: "Marreta de 1 Kg", uni: "PÇ", qty: 1 },
  { num: 5, desc: "Pincel Pequeno (15 cm)", uni: "PÇ", qty: 1 },
  { num: 6, desc: "Gabarito / Molde alfabeto e Números", uni: "CJ", qty: 1 },
  { num: 7, desc: "Lata de tinta pequena (50 ml)", uni: "PÇ", qty: 1 },
  { num: 8, desc: "Chave de boca 16", uni: "PÇ", qty: 1 },
  { num: 9, desc: "Parafuso Vazado (dispositivo para selar)", uni: "PÇ", qty: 5 },
  { num: 10, desc: "Conector Bimetálico (Parafuso fendido)", uni: "PÇ", qty: 5 },
  { num: 11, desc: "Parafuso terminal para Aterramento", uni: "PÇ", qty: 5 },
  { num: 12, desc: "Fita Isolante tamanho Médio – 05 metros", uni: "PÇ", qty: 1 },
  { num: 13, desc: "Fita Alta Fusão – 05 Metros", uni: "PÇ", qty: 1 },
  { num: 14, desc: "Visor para Caixa de Medição tamanho Padrão", uni: "PÇ", qty: 5 },
  { num: 15, desc: "Disjuntor Monopolar de 40A", uni: "PÇ", qty: 3 },
  { num: 16, desc: "Disjuntor Monopolar de 70A", uni: "PÇ", qty: 2 },
  { num: 17, desc: "Disjuntor Bipolar de 60A", uni: "PÇ", qty: 2 },
  { num: 18, desc: "Disjuntor Tripolar de 50A", uni: "PÇ", qty: 1 },
  { num: 19, desc: "Disjuntor Tripolar de 60A", uni: "PÇ", qty: 1 },
  { num: 20, desc: "Parafuso para fixação de Medidor à caixa Medição", uni: "PÇ", qty: 5 },
  { num: 21, desc: "Parafuso para fixação de Medidor ao Cavalete", uni: "PÇ", qty: 5 },
  { num: 22, desc: "Tampão para vedação de furos de caixa Monofásica", uni: "PÇ", qty: 5 },
  { num: 23, desc: "Tampão para vedação de furos de caixa Polifásica", uni: "PÇ", qty: 5 },
  { num: 24, desc: "Terminal Tubular de Cobre para cabo 6mm", uni: "PÇ", qty: 5 },
  { num: 25, desc: "Terminal Tubular de Cobre para cabo 10mm", uni: "PÇ", qty: 5 },
  { num: 26, desc: "Terminal Tubular de Cobre para cabo 16mm", uni: "PÇ", qty: 5 },
  { num: 27, desc: "Terminal Tubular de Cobre para cabo 25mm", uni: "PÇ", qty: 5 },
  { num: 28, desc: "Terminal Tubular de Cobre para cabo 50mm", uni: "PÇ", qty: 5 },
  { num: 29, desc: "Flanela / estopa para limpeza", uni: "PÇ", qty: 1 },
  { num: 30, desc: "1 metro de cabo de cobre 6mm (para rabicho)", uni: "M", qty: 1 },
  { num: 31, desc: "1 metro de cabo de cobre 10mm (para rabicho)", uni: "M", qty: 1 },
  { num: 32, desc: "1 metro de cabo de cobre 16mm (para rabicho)", uni: "M", qty: 1 },
];

const es2ChecklistVeiculo = [
  "Veículo próprio",
  "Veículo locado",
  "Documentação atualizada",
  "Controle de manutenção do veículo (físico ou digital)",
  "Câmera veicular",
  "Rastreador veicular",
  "Sistema de Amarração de Escadas",
  "Pneu em condições de uso (s/ reformar eixo diant.)",
  "Pneu de mesmo desenho no mesmo eixo",
  "Identificação 'à serviço da CEMIG'",
  "Funilaria em boas condições",
  "Todas as setas em correto funcionamento",
  "Farol alto e baixo em correto funcionamento",
  "Giroflex",
  "Silibim (iluminação auxiliar)",
  "Buzina em correto funcionamento",
  "Kit resgate (fabricante Soluções)",
];

const es2ChecklistEscada = [
  "SEM EQUIPAMENTO",
  "Escada giratória em correto funcionamento",
  "Placa de identificação da torre",
  "Laudo da escada giratória",
  "Controle de manutenção da escada (físico ou digital)",
  "Equipamento com fabricação menor a 15 anos",
  "Equipamento com gráfico de carga visível",
  "Placa de identificação da cesta aérea",
  "Laudo de inspeção de manutenção válido",
  "Manutenção anual válida",
  "Laudo de emissão acústica válido (4 em 4 anos)",
  "Controles identificados e protegidos contra uso inadvertido",
  "Ponto de aterramento no chassi e equipamento",
  "Inclinômetro",
  "Bloqueio de sapata por braço fora do berço",
  "Válvula de segurança com holding dos cilindros do braço",
  "Ponto de ancoragem",
  "Sistema de parada de emergência inferior e superior",
  "Sistema de operação de emergência",
  "Sistema de nivelamento da cesta aérea",
  "Liner e teste para 46 kV (inserir validade do laudo nas observações)",
];

// ════════════════════════════════════════════════════════
// DATA - EL2
// ════════════════════════════════════════════════════════
const el2Ferramentas = [
  { num: 1, desc: "Alicate bomba d'água com cabo isolado", uni: "Pç", qty: 2 },
  { num: 3, desc: "Alicate de compressão mecânica (com corda e gancho) (OPCIONAL se substituído por alicate de compressão hidráulico)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 4, desc: "Alicate de compressão eletro-hidráulico (com corda e gancho) (*)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Solução", "Hubbel", "Izumi", "Grenlee"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 5, desc: "Alicate profissional com cabo isolado", uni: "Pç", qty: 2 },
  { num: 6, desc: "Amperímetro, voltímetro, ohmímetro, alicate, digital, display LCD", uni: "Pç", qty: 2, laudo: 3, fabs: ["Hidramaq", "Solução", "Hubbel", "Izumi", "Grenlee"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 7, desc: "Analisador de Desvio de Registros (**)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Montrel"] },
  { num: 9, desc: "Bandeirolas para sinalização e suporte para fixação", uni: "Pç", qty: 10 },
  { num: 11, desc: "Bastão pega-tudo cabeçote alumínio 32mm x 2600mm e sacola para acondicionar", uni: "Pç", qty: 1, laudo: 1, fabs: ["Terex"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 12, desc: "Binóculo", uni: "Pç", qty: 1 },
  { num: 13, desc: "Bolsa de lona porta fusível", uni: "Pç", qty: 1 },
  { num: 15, desc: "Cabeçote para corte de ramal de ligação até 35 mm²", uni: "Pç", qty: 1 },
  { num: 17, desc: "Calibrador portátil para ensaio em medidor kWh eletromecânico e eletrônico (**)", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 20, desc: "Calço emborrachado para veículo (veículos com estabilizador deverão também conter calços poliméricos para as sapatas)", uni: "Pç", qty: 2 },
  { num: 25, desc: "Câmera veicular conforme especificação da IT-RD-00022", uni: "Pç", qty: 1 },
  { num: 26, desc: "Canivete", uni: "Pç", qty: 2 },
  { num: 32, desc: "Cavadeira com socador, comprimento de 1500 mm", uni: "Pç", qty: 1 },
  { num: 36, desc: "Chave canhão de 3/8\" isolada (isolamento de cabo e extensão) – isolamento >= 1kV", uni: "Pç", qty: 2 },
  { num: 37, desc: "Chave canhão de 7/16\" isolada (isolamento de cabo e extensão) – isolamento >= 1kV", uni: "Pç", qty: 2 },
  { num: 38, desc: "Chave com catraca com cabo isolado para aplicação de conector perfuração", uni: "Pç", qty: 2 },
  { num: 39, desc: "Chave de fenda isolada (isolamento de cabo e extensão) 6,5 x 150mm", uni: "Pç", qty: 2 },
  { num: 40, desc: "Chave de fenda isolada (isolamento de cabo e extensão) 3 x 100mm", uni: "Pç", qty: 2 },
  { num: 41, desc: "Chave de fenda isolada (isolamento de cabo e extensão) 5,5 x 150mm", uni: "Pç", qty: 2 },
  { num: 42, desc: "Chave de impacto a bateria 180 Nm (com corda e gancho)", uni: "Pç", qty: 1 },
  { num: 43, desc: "Chave Phillips isolada (isolamento de cabo e extensão) 6 x 150mm", uni: "Pç", qty: 2 },
  { num: 44, desc: "Chave Phillips isolada (isolamento de cabo e extensão) 3 x 100mm (**)", uni: "Pç", qty: 1 },
  { num: 45, desc: "Chave inglesa 200mm isolada", uni: "Pç", qty: 2 },
  { num: 46, desc: "Chave inglesa 300mm isolada", uni: "Pç", qty: 2 },
  { num: 49, desc: "Cone de sinalização, altura mínima 700mm", uni: "Pç", qty: 10 },
  { num: 50, desc: "Conjunto chave allen em mm de 8; 6; 5; 4; 3; 2,5 e 2", uni: "Cj", qty: 1 },
  { num: 51, desc: "Conjunto chave allen em polegadas de 1/4; 7/32; 3/16; 5/32; 9/64; 1/8; 7/64; 3/32 e 5/64", uni: "Cj", qty: 1 },
  { num: 52, desc: "Chave hexagonal Allen 5 mm, tipo T", uni: "Pç", qty: 1 },
  { num: 53, desc: "Conjunto de aterramento temporário para baixa tensão", uni: "Cj", qty: 1, laudo: 2, fabs: ["Terex", "Solução", "FCP"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 55, desc: "Conjunto de aterramento temporário para média tensão trifásico", uni: "Cj", qty: 1, laudo: 2, fabs: ["Terex", "Solução", "FCP"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 56, desc: "Conjunto de aterramento temporário sela com grampo de aterramento e haste", uni: "Cj", qty: 1, laudo: 3, fabs: ["Terex"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 57, desc: "Crachá de identificação", uni: "Pç", qty: 2 },
  { num: 61, desc: "Detector de MT de 1 a 35 kV", uni: "Pç", qty: 1, laudo: 1, fabs: ["Terex", "Solução", "Lider", "Steetc"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 63, desc: "Dinamômetro 45 kgf para teste de padrão de entrada", uni: "Pç", qty: 1, laudo: 1, fabs: [], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 64, desc: "Dispositivo anti-queda de cartucho", uni: "Pç", qty: 1 },
  { num: 66, desc: "Dispositivo de abertura em carga para MT", uni: "Pç", qty: 1, laudo: 1, fabs: ["Leal", "S&C", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 67, desc: "Dispositivo de fixação de placas de advertência", uni: "Pç", qty: 5 },
  { num: 68, desc: "Dispositivos instaladores de linha de vida (agulhão + gancho)", uni: "Cj", qty: 1 },
  { num: 74, desc: "Equipamento de comunicação de dados e voz conforme especificação da Contratante (incluindo câmera fotográfica e GPS)", uni: "Pç", qty: 1 },
  { num: 75, desc: "Escada de extensão 2 x 4,25m (± 0,5m) de fibra", uni: "Pç", qty: 2 },
  { num: 76, desc: "Escada singela 1 x 3,50m (± 0,5m) de fibra", uni: "Pç", qty: 1 },
  { num: 77, desc: "Escova de aço tubular para condutores", uni: "Pç", qty: 2 },
  { num: 78, desc: "Espora de aço DT", uni: "Pç", qty: 2 },
  { num: 80, desc: "Esticador com correia ou moitão de 2 gornes para condutores CA/CAA", uni: "Pç", qty: 1 },
  { num: 86, desc: "Ferramenta para aplicação de conector cunha (para chave de impacto)", uni: "Pç", qty: 1 },
  { num: 87, desc: "Ferramenta para inspeção de poste de madeira", uni: "Pç", qty: 1 },
  { num: 88, desc: "Fita de isolamento com recolhedor, zebrada amarela e preta 50 mm x 40 m", uni: "Pç", qty: 2 },
  { num: 92, desc: "Garra para cabo CA/CAA 6 a 1/0", uni: "Pç", qty: 1 },
  { num: 94, desc: "Grampo para aterramento temporário chave fusível", uni: "Pç", qty: 3 },
  { num: 95, desc: "Grampo prendedor de lençol", uni: "Pç", qty: 8 },
  { num: 96, desc: "Impressora Térmica Portátil", uni: "Pç", qty: 1, laudo: 1, hasSN: false, hasValidade: false, hasLaudoName: false, fabs: ["ZEBRA RW420", "ZEBRA ZQ520", "ZEBRA ZQ521", "BIXOLON XM7-40"] },
  { num: 97, desc: "Inflador ou testador de luvas de borracha (*)", uni: "Pç", qty: 1 },
  { num: 99, desc: "Kit Antirreprova (**)", uni: "Pç", qty: 1 },
  { num: 100, desc: "Lâmina de serra", uni: "Pç", qty: 1 },
  { num: 101, desc: "Lanterna", uni: "Pç", qty: 2 },
  { num: 102, desc: "Lençol de borracha isolante para BT e sacola para acondicionar", uni: "Pç", qty: 10, laudo: 10, labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 105, desc: "Lima murça chata", uni: "Pç", qty: 1 },
  { num: 107, desc: "Marreta de aço de 2,5 kg", uni: "Pç", qty: 1 },
  { num: 108, desc: "Martelo bola", uni: "Pç", qty: 1 },
  { num: 111, desc: "Matriz para alicate mecânico (162, 163, 236, 237, 238, 239, 242, 243 e 245)", uni: "Cj", qty: 1 },
  { num: 120, desc: "Parafusadeira a bateria com engate rápido para bit hexagonal de 1/4", uni: "Pç", qty: 1 },
  { num: 122, desc: "Placa de advertência 'não opere esta chave'", uni: "Pç", qty: 5 },
  { num: 125, desc: "Ponteiro de aço 1/2 pol de mão", uni: "Pç", qty: 1 },
  { num: 128, desc: "Registrador de tensão e Corrente BT - Mód. 8 PRODIST com GPRS", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 129, desc: "Sacola para ferramentas", uni: "Un", qty: 1 },
  { num: 130, desc: "Sacola, p/ bastão telescópico (vara manobra) c/ terminal universal", uni: "Pç", qty: 1 },
  { num: 132, desc: "Serrote curvo para poda", uni: "Pç", qty: 1 },
  { num: 133, desc: "Sonda boroscópica 5m", uni: "Pç", qty: 1 },
  { num: 134, desc: "Sonda, passa fio, cabo de 20 m", uni: "Pç", qty: 1 },
  { num: 135, desc: "Suporte isolado para 1000 V,", uni: "Pç", qty: 1 },
  { num: 138, desc: "Tesourão articulado 750mm (com corda e gancho)", uni: "Pç", qty: 1 },
  { num: 141, desc: "Trena de fibra de 50m", uni: "Pç", qty: 1 },
  { num: 142, desc: "Vara, manobra, telescópica, 7 seções, fibra", uni: "Pç", qty: 1, laudo: 1, fabs: ["Hidramaq", "Tec-Ali", "Hubbel", "Solução"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
];

const el2Epis = [
  { num: 144, desc: "Bolsa de Lona para acondicionar capacete, luva de vaqueta e óculos", uni: "Un", qty: 2 },
  { num: 145, desc: "Bolsa de Lona para acondicionar manga isolante", uni: "Un", qty: 2 },
  { num: 146, desc: "Bolsa para acondicionar luva isolante", uni: "Un", qty: 4 },
  { num: 147, desc: "Botina de Segurança com cadarço", uni: "Pr", qty: 4 },
  { num: 148, desc: "Calça de Uniforme com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas, com logotipo empresa", uni: "Un", qty: 6 },
  { num: 149, desc: "Camisa de Uniforme manga longa com Tecido Resistente à Chama – condutibilidade, inflamabilidade e influências eletromagnéticas com logotipo empresa", uni: "Un", qty: 6 },
  { num: 150, desc: "Capacete de segurança, classe B, com aba frontal e jugular", uni: "Un", qty: 2 },
  { num: 151, desc: "Capuz de proteção solar com tecido Resistente à Chama", uni: "Un", qty: 2 },
  { num: 153, desc: "Capa impermeável para chuva (calça e blusa separadas, com faixa reflexiva)", uni: "Un", qty: 2 },
  { num: 154, desc: "Carretilha de dupla ação com corda e gancho para trabalho e resgate", uni: "Un", qty: 2, laudo: 3 },
  { num: 155, desc: "Conjunto cinto paraquedista, talabarte de posicionamento com mosquetão de alumínio tripla trava e trava quedas", uni: "Cj", qty: 2, laudo: ["Cinto", "Talabarte", "Trava Quedas", "Cinto", "Talabarte", "Trava Quedas", "Cinto", "Talabarte", "Trava Quedas"], hasSN: false },
  { num: 157, desc: "Corda de linha de vida 12mm – normatizadas pela NR18 (Cabos de fibra sintética) – 15 metros", uni: "Pç", qty: 2 },
  { num: 159, desc: "Garrafa térmica de 5 litros (1 garrafa para cada 2 pessoas)", uni: "Un", qty: 1 },
  { num: 160, desc: "Jaqueta de Uniforme com Tecido Resistente à Chama (OPCIONAL, de acordo com a necessidade da região)", uni: "Un", qty: 2 },
  { num: 161, desc: "Luva de borracha isolante 0,5kV (classe 00)", uni: "Pr", qty: 2, laudo: ["Luva 1", "Luva 2", "Luva 1", "Luva 2", "Luva 1", "Luva 2"], fabs: ["Salisbury", "Northsafety", "GB", "Orion"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 162, desc: "Luva de borracha Isolante 17kV (classe 2) ou 26,5kV (classe 3) – Conforme nível de tensão da região", uni: "Pr", qty: 2, laudo: ["Luva 1", "Luva 2", "Luva 1", "Luva 2", "Luva 1", "Luva 2"], fabs: ["Salisbury", "Northsafety", "GB", "Orion"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 165, desc: "Luva de couro para proteção da luva de borracha isolante", uni: "Pr", qty: 4 },
  { num: 166, desc: "Luva de vaqueta para trabalho leve", uni: "Pr", qty: 2 },
  { num: 167, desc: "Manga isolante para 1kV – (Classe 0)", uni: "Pr", qty: 2, laudo: ["Manga 1", "Manga 2", "Manga 1", "Manga 2", "Manga 1", "Manga 2"], fabs: ["Salisbury", "GB"], labs: ["Oficina do Alicate", "ITRA", "REMO", "CTMIG", "Helite", "BHMIG", "GLOBALTEK"] },
  { num: 168, desc: "Mosquetão de aço dupla trava 22kN (para pontos de ancoragem)", uni: "Pç", qty: 4 },
  { num: 169, desc: "Óculos de segurança incolor para proteção de partículas multidirecionais", uni: "Un", qty: 2 },
  { num: 170, desc: "Óculos de segurança lente escura tonalidade 2 ou 3 para proteção de partículas multidirecionais", uni: "Un", qty: 2 },
  { num: 171, desc: "Perneira de couro sem partes metálicas ou Bota de Campanha", uni: "Pr", qty: 2 },
  { num: 173, desc: "Protetor solar FPS 30", uni: "Un", qty: 2 },
  { num: 174, desc: "Sacola de Lona para acondicionar ferramenta e EPIs (catarina)", uni: "Un", qty: 2 },
  { num: 175, desc: "Sacola de Lona para acondicionar linha de vida e cinto", uni: "Un", qty: 2 },
];

const el2Kit = [
  { num: 1, desc: "Caixa de ferramentas para acondicionamento dos itens – Capacidade Média 10L", uni: "PÇ", qty: 1 },
  { num: 2, desc: "Cadeado médio", uni: "PÇ", qty: 1 },
  { num: 3, desc: "Talhadeira tamanho Médio (25 cm)", uni: "PÇ", qty: 1 },
  { num: 4, desc: "Marreta de 1 Kg", uni: "PÇ", qty: 1 },
  { num: 5, desc: "Pincel Pequeno (15 cm)", uni: "PÇ", qty: 1 },
  { num: 6, desc: "Gabarito / Molde alfabeto e Números", uni: "CJ", qty: 1 },
  { num: 7, desc: "Lata de tinta pequena (50 ml)", uni: "PÇ", qty: 1 },
  { num: 8, desc: "Chave de boca 16", uni: "PÇ", qty: 1 },
  { num: 9, desc: "Parafuso Vazado (dispositivo para selar)", uni: "PÇ", qty: 5 },
  { num: 10, desc: "Conector Bimetálico (Parafuso fendido)", uni: "PÇ", qty: 5 },
  { num: 11, desc: "Parafuso terminal para Aterramento", uni: "PÇ", qty: 5 },
  { num: 12, desc: "Fita Isolante tamanho Médio – 05 metros", uni: "PÇ", qty: 1 },
  { num: 13, desc: "Fita Alta Fusão – 05 Metros", uni: "PÇ", qty: 1 },
  { num: 14, desc: "Visor para Caixa de Medição tamanho Padrão", uni: "PÇ", qty: 5 },
  { num: 15, desc: "Disjuntor Monopolar de 40A", uni: "PÇ", qty: 3 },
  { num: 16, desc: "Disjuntor Monopolar de 70A", uni: "PÇ", qty: 2 },
  { num: 17, desc: "Disjuntor Bipolar de 60A", uni: "PÇ", qty: 2 },
  { num: 18, desc: "Disjuntor Tripolar de 50A", uni: "PÇ", qty: 1 },
  { num: 19, desc: "Disjuntor Tripolar de 60A", uni: "PÇ", qty: 1 },
  { num: 20, desc: "Parafuso para fixação de Medidor à caixa Medição", uni: "PÇ", qty: 5 },
  { num: 21, desc: "Parafuso para fixação de Medidor ao Cavalete", uni: "PÇ", qty: 5 },
  { num: 22, desc: "Tampão para vedação de furos de caixa Monofásica", uni: "PÇ", qty: 5 },
  { num: 23, desc: "Tampão para vedação de furos de caixa Polifásica", uni: "PÇ", qty: 5 },
  { num: 24, desc: "Terminal Tubular de Cobre para cabo 6mm", uni: "PÇ", qty: 5 },
  { num: 25, desc: "Terminal Tubular de Cobre para cabo 10mm", uni: "PÇ", qty: 5 },
  { num: 26, desc: "Terminal Tubular de Cobre para cabo 16mm", uni: "PÇ", qty: 5 },
  { num: 27, desc: "Terminal Tubular de Cobre para cabo 25mm", uni: "PÇ", qty: 5 },
  { num: 28, desc: "Terminal Tubular de Cobre para cabo 50mm", uni: "PÇ", qty: 5 },
  { num: 29, desc: "Flanela / estopa para limpeza", uni: "PÇ", qty: 1 },
  { num: 30, desc: "1 metro de cabo de cobre 6mm (para rabicho)", uni: "M", qty: 1 },
  { num: 31, desc: "1 metro de cabo de cobre 10mm (para rabicho)", uni: "M", qty: 1 },
  { num: 32, desc: "1 metro de cabo de cobre 16mm (para rabicho)", uni: "M", qty: 1 },
];

const el2ChecklistVeiculo = [
  "Veículo próprio",
  "Veículo locado",
  "Documentação atualizada",
  "Controle de manutenção do veículo (físico ou digital)",
  "Câmera veicular",
  "Rastreador veicular",
  "Sistema de Amarração de Escadas",
  "Pneu em condições de uso (s/ reformar eixo diant.)",
  "Pneu de mesmo desenho no mesmo eixo",
  "Identificação 'à serviço da CEMIG'",
  "Funilaria em boas condições",
  "Todas as setas em correto funcionamento",
  "Farol alto e baixo em correto funcionamento",
  "Giroflex",
  "Silibim (iluminação auxiliar)",
  "Buzina em correto funcionamento",
  "Kit resgate (fabricante Soluções)",
];

const el2ChecklistEscada = [
  "SEM EQUIPAMENTO",
  "Escada giratória em correto funcionamento",
  "Placa de identificação da torre",
  "Laudo da escada giratória",
  "Controle de manutenção da escada (físico ou digital)",
  "Equipamento com fabricação menor a 15 anos",
  "Equipamento com gráfico de carga visível",
  "Placa de identificação da cesta aérea",
  "Laudo de inspeção de manutenção válido",
  "Manutenção anual válida",
  "Laudo de emissão acústica válido (4 em 4 anos)",
  "Controles identificados e protegidos contra uso inadvertido",
  "Ponto de aterramento no chassi e equipamento",
  "Inclinômetro",
  "Bloqueio de sapata por braço fora do berço",
  "Válvula de segurança com holding dos cilindros do braço",
  "Ponto de ancoragem",
  "Sistema de parada de emergência inferior e superior",
  "Sistema de operação de emergência",
  "Sistema de nivelamento da cesta aérea",
  "Liner e teste para 46 kV (inserir validade do laudo nas observações)",
];
